version: '3.8'

services:
  # Servicio MongoDB
  db:
    image: mongo:latest
    container_name: egg_detection_mongo
    ports:
      - "27017:27017"  # Puerto para MongoDB
    volumes:
      - mongo_data:/data/db  # Persistencia de datos
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Servicio MinIO
  minio:
    image: minio/minio:latest
    container_name: egg_detection_minio
    ports:
      - "9000:9000"  # Puerto para MinIO API
      - "9001:9001"  # Puerto para la consola web de MinIO
    volumes:
      - minio_data:/data  # Persistencia de datos
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  # Servicio API
  # api:
  #   build: .
  #   container_name: egg_detection_api
  #   ports:
  #     - "8000:8000"  # Puerto para la API
  #   depends_on:
  #     - db
  #     - minio
  #   environment:
  #     MONGO_URI: mongodb://root:example@egg_detection_mongo:27017
  #     DATABASE_NAME: egg_viability_db

volumes:
  mongo_data:
  minio_data: